---
- name: Create Pre-Auth Key
  command:
    cmd: docker exec headscale headscale --user {{ item }} preauthkeys create --expiration {{ exp_time }}
    chdir: /opt/headscale
  register: pre_auth_output
  failed_when: "'No such container' in pre_auth_output.stderr"
  tags:
    - create_preauth
  loop: "{{ pre_auth_user }}"

- name: Write pre-auth keys to a local YAML file
  delegate_to: localhost
  connection: local
  become: false
  template:
    src: pre_auth.j2
    dest: ./roles/headscale/files/pre_auth_keys.yml
  vars:
    pre_auth_keys: "{{ pre_auth_output.results }}"
  tags:
    - write_preauth

- name: Encrypt the pre-auth keys YAML file
  local_action:
    module: command
    cmd: ansible-vault encrypt ./roles/headscale/files/pre_auth_keys.yml
  become: false
  tags:
    - encrypt_preauth
