---
- name: Create Pre-Auth Key
  shell:
    cmd: docker exec headscale headscale -u {{ item }} preauthkeys create -e {{ exp_time_preauthkeys }} --reusable | grep -Eo '[a-f0-9]{48}'
    chdir: /opt/headscale
  register: pre_auth_output
  failed_when: "'User not found' in pre_auth_output.stderr" 
  loop: "{{ pre_auth_user }}"

- name: print
  debug:
    msg: "result = {{ pre_auth_output.results | map(attribute='stdout') | list }}"

- name: Extract preauthkey
  set_fact:
    preauthkey: "{{ pre_auth_output.results | map(attribute='stdout') | list }}"

- name: Write keys to output file
  delegate_to: localhost
  become: false
  template:
    src: pre_auth.j2
    dest: "/tmp/pre_auth_keys.yml"
