---
- name: Check if /etc/sysctl.conf.bak already exists
  stat:
    path: /etc/sysctl.conf.bak
  register: backup_check

- name: Create backup of Sysctl.conf file if backup doesn't exist
  copy:
    src: /etc/sysctl.conf
    dest: /etc/sysctl.conf.bak
    remote_src: yes
  when: not backup_check.stat.exists

- name: Enable IPv4 forwarding in sysctl.conf
  lineinfile:
    path: /etc/sysctl.conf
    line: "net.ipv4.ip_forward = 1"
    create: yes

- name: Enable IPv6 forwarding in sysctl.conf
  lineinfile:
    path: /etc/sysctl.conf
    line: "net.ipv6.conf.all.forwarding = 1"
    create: yes

- name: Apply sysctl changes
  command:
    cmd: sysctl -p /etc/sysctl.conf

- name: Set as Exit Node
  command:
    cmd: tailscale set --advertise-exit-node
