---
- name: Install Apache2
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Enable apache2
  command:
    cmd: systemctl enable apache2

- name: Start apache2
  command:
    cmd: systemctl start apache2

- name: Setup Apache2
  include_tasks: "setup.yml"
  tags: "setup_apache2"
