---
- name: Ensure errorpage directory exists
  file:
    path: /var/www/html/errorpage
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"

- name: Copy custom error page
  copy:
    src: "{{ ansible_dir }}/asset/"
    dest: /var/www/html/errorpage/
    owner: www-data
    group: www-data
    mode: "0644"

- name: Enable Apache2 modules
  command: a2enmod {{ item }}
  loop:
    - rewrite
    - headers
    - ssl
    - proxy
    - proxy_http
  notify: Reload Apache

- name: Generate apache2 Site Conf File
  template:
    src: "templates/000-default.j2"
    dest: "/etc/apache2/sites-available/000-default.conf"

- name: Copy redirect.rules from localmachine
  copy:
    src: "files/redirect.rules"
    dest: "/etc/apache2/redirect.rules"

- name: Check if ports.conf exists
  stat:
    path: /etc/apache2/ports.conf
  register: ports_file

- name: Get contents of ports.conf
  slurp:
    src: /etc/apache2/ports.conf
  register: file_contents
  when: ports_file.stat.exists

- name: Decode file_contents
  set_fact:
    decoded_contents: "{{ file_contents['content'] | b64decode }}"
  when: ports_file.stat.exists

- name: Ensure 'Listen 80' does not exist in ports.conf
  lineinfile:
    path: /etc/apache2/ports.conf
    line: "Listen 8080"
    insertafter: EOF
  when: "'Listen 80' not in decoded_contents"

- name: Change 'Listen 80' to 'Listen 8080' in ports.conf
  replace:
    path: /etc/apache2/ports.conf
    regexp: "^Listen 80$"
    replace: "Listen 8080"
  when: "'Listen 80' in decoded_contents"

- name: Check if certificate already exists
  stat:
    path: "/etc/letsencrypt/live/{{ domain_phish }}/fullchain.pem"
  register: cert_file

- name: Fail if certificate does not exist
  fail:
    msg: "The certificate file does not exist!"
  when: not cert_file.stat.exists

- name: Find the correct certificate directory
  find:
    paths: "/etc/letsencrypt/live/"
    patterns: "{{ domain_phish }}*"
  register: cert_directories

- name: Create symlink to the correct certificate directory
  file:
    src: "{{ cert_directories.files[0].path }}"
    dest: "/etc/letsencrypt/live/{{ domain_phish }}"
    state: link
  when: cert_directories.matched > 0

- name: Fetch fullchain.key and priv.key
  fetch:
    src: "/etc/letsencrypt/live/{{ domain_phish }}/{{ item }}"
    dest: "{{ ansible_dir }}/roles/gophish/files/admin_{{ item }}"
    flat: yes
  loop:
    - fullchain.pem
    - key.pem

- name: Rename key.pem to privkey.pem on local machine
  command: 
    cmd: mv "{{ ansible_dir }}/roles/gophish/files/admin_key.pem" "{{ ansible_dir }}/roles/gophish/files/admin_privkey.pem"
  delegate_to: localhost
  become: no

- name: Check Apache configuration
  command: apachectl configtest
  register: result
  changed_when: False
  failed_when:
    - "'Syntax OK' not in result.stderr_lines"
  notify: Reload Apache
