---
- name: Set certbot package for redirector.phish
  set_fact:
    certbot_package: "python3-certbot-apache"
  when: 
    - redirector.phish is defined
    - inventory_hostname in redirector.phish or inventory_hostname == redirector.phish

- name: Set certbot package for other hosts
  set_fact:
    certbot_package: "python3-certbot-nginx"
  when: redirector.phish is not defined or (redirector.phish is defined and inventory_hostname not in redirector.phish)

- name: Install Certbot
  apt:
    name:
      - python3-certbot
      - "{{ certbot_package }}"
    state: present
    update_cache: yes
