---
- name: Add the Tailscale apt key [Ubuntu]
  apt_key:
    url: https://pkgs.tailscale.com/stable/ubuntu/focal.gpg
  when: ansible_os_family == "Debian" and inventory_hostname != 'headscale'

- name: Add the Tailscale apt repository [Ubuntu]
  apt_repository:
    repo: "deb [arch=amd64] https://pkgs.tailscale.com/stable/ubuntu focal main"
    update_cache: yes
  when: ansible_os_family == "Debian" and inventory_hostname != 'headscale'

- name: Install tailscale [Ubuntu]
  apt:
    name: tailscale
    state: present
  when: ansible_os_family == "Debian" and inventory_hostname != 'headscale'
