---
- name: Ensure Evilnginx directory
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ path_dir_evilginx }}"
    - "{{ path_dir_evilginx }}/phishlets"
    - "{{ path_dir_evilginx }}/config"
    - "{{ path_dir_evilginx }}/config/crt"

- name: Transfer Dockerfile of Evilginx 3
  copy:
    src: "files/{{ item }}"
    dest: "{{ path_dir_evilginx }}/{{ item }}"
  loop:
    - Dockerfile

- name: Generate docker-compose Config from Template
  template:
    src: templates/docker_compose.j2
    dest: "{{ path_dir_evilginx }}/docker-compose.yml"

- name: Generate Evilginx Config from Template
  template:
    src: templates/evilginx_config.j2
    dest: "{{ path_dir_evilginx }}/config/config.json"

- name: Transfer Phishlets
  copy:
    src: "files/{{ phishlets_name }}.yaml"
    dest: "{{ path_dir_evilginx }}/phishlets/{{ phishlets_name }}.yaml"

- name: Build evilginx2 Docker image
  command:
    cmd: docker build --no-cache --pull -t evilginx2:latest "{{ path_dir_evilginx }}"
  register: build_result
  failed_when:
    - "'Error' in build_result.stdout"
    - "'Error' in build_result.stderr"

- name: Transfer and rename admin_fullchain.pem to ca.crt
  copy:
    src: "roles/gophish/files/admin_fullchain.pem"
    dest: "{{ path_dir_evilginx }}/config/crt/ca.crt"
    owner: root
    group: root
    mode: "0644"

- name: Transfer admin_privkey.pem
  copy:
    src: "roles/gophish/files/admin_privkey.pem"
    dest: "{{ path_dir_evilginx }}/config/crt/admin_privkey.pem"
    owner: root
    group: root
    mode: "0600"

- name: Convert PKCS Format
  command:
    cmd: openssl rsa -in admin_privkey.pem -out admin_privkey_traditional.pem
    chdir: "{{ path_dir_evilginx }}/config/crt"

- name: Delete admin_privkey.pem
  file:
    path: "{{ path_dir_evilginx }}/config/crt/admin_privkey.pem"
    state: absent

- name: Rename Certificate Key File
  copy:
    src: "{{ path_dir_evilginx }}/config/crt/admin_privkey_traditional.pem"
    dest: "{{ path_dir_evilginx }}/config/crt/ca.key"
    remote_src: yes

- name: Remove old file
  file:
    path: "{{ path_dir_evilginx }}/config/crt/admin_privkey_traditional.pem"
    state: absent

- name: Run Gophish Docker Compose
  docker_compose:
    project_src: "{{ path_dir_evilginx }}"
    state: present
    restarted: yes
