---
- name: Run Terraform on all segments
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Check if project directory exists
      stat:
        path: "{{ ursaops_root }}/terraform/{{ project_name }}"
      register: project_directory

    - name: Fail if project directory does not exist
      fail:
        msg: "The specified project directory {{ ursaops_root }}/terraform/{{ project_name }} does not exist!"
      when: not project_directory.stat.exists

    - name: Find all main.tf files
      find:
        paths: "{{ ursaops_root }}/terraform/{{ project_name }}"
        patterns: "main.tf"
        recurse: yes
      register: main_tf_files
      when: project_directory.stat.exists

    - name: Display main.tf files on each segment
      debug:
        var: main_tf_files.files | map(attribute='path') | list

    - name: Execute Terraform init on each segment
      command: "terraform init"
      args:
        chdir: "{{ item | dirname }}"
      loop: "{{ main_tf_files.files | map(attribute='path') | list }}"
    
    - name: Execute Terraform plan on each segment
      command: "terraform plan -out=plan.out"
      args:
        chdir: "{{ item | dirname }}"
      loop: "{{ main_tf_files.files | map(attribute='path') | list }}"
    
    # - name: Execute Terraform apply on each segment
    #   command: "terraform apply -auto-approve plan.out"
    #   args:
    #     chdir: "{{ item | dirname }}"
    #   loop: "{{ main_tf_files.files | map(attribute='path') | list }}"
  tags: "terraform_apply"

- name: Check Terraform State
  hosts: localhost
  connection: local
  tasks:
    - name: Check Terraform State
      command:
        cmd: "terraform plan -no-color"
        chdir: "{{ segment_paths[segment] }}"
      register: terraform_output

    - name: Display Terraform plan output
      debug:
        msg: "{{ terraform_output.stdout }}"
  tags: "terraform_state"

- name: Generate Ansible Inventory
  hosts: localhost
  connection: local
  tasks:
    - name: Merge Terraform-generated inventories
      command:
        cmd: "python3 generate_inventory.py"
        chdir: "../"
  tags: "create_inventory"

# - name: Create Ansible Vault
#   hosts: localhost
#   connection: local
#   tasks:
#     - name: Initialize Terraform
#       command:
#         cmd: "terraform init"
#         chdir: "./terraform/environment/dev/phishing_segment/"
#   tags: "create_vault"

- name: Destroy VM segments
  hosts: localhost
  connection: local
  serial: 1

  tasks:
    - name: Set the segment paths for all
      set_fact:
        target_segments: "{{ segment_paths }}"
      when: segment == 'all'

    - name: Set the segment path for specific segment
      set_fact:
        target_segments: { "{{ segment }}": "{{ segment_paths[segment] }}" }
      when: segment != 'all'

    - name: Initialize Terraform
      command:
        cmd: "terraform init "
        chdir: "{{ item.value }}"
      loop: "{{ target_segments|dict2items }}"
      loop_control:
        label: "{{ item.key }}"

    - name: Plan Terraform destruction and output to file
      command:
        cmd: "terraform plan -destroy -out=tfplan "
        chdir: "{{ item.value }}"
      loop: "{{ target_segments|dict2items }}"
      register: terraform_plan_output
      loop_control:
        label: "{{ item.key }}"

    - debug:
        var: terraform_plan_output.stdout_lines

    # Pause and ask for manual confirmation
    - pause:
        prompt: "Review the Terraform destroy plan for segment {{ item.key }}. Press enter to continue with destroy or Ctrl+C to abort."
      loop: "{{ target_segments|dict2items }}"
      loop_control:
        label: "{{ item.key }}"

    - name: Apply Terraform destruction using the saved plan
      command:
        cmd: "terraform apply tfplan "
        chdir: "{{ item.value }}"
      loop: "{{ target_segments|dict2items }}"
      register: terraform_destroy_output
      loop_control:
        label: "{{ item.key }}"

    - debug:
        msg: "Segment {{ item.item.key }} was successfully destroyed."
      loop: "{{ terraform_destroy_output.results }}"
      when: item.rc == 0 # Checking if the command exit code was successful

    - debug:
        msg: "Segment {{ item.item.key }} failed to destroy. Please review the logs."
      loop: "{{ terraform_destroy_output.results }}"
      when: item.rc != 0 # Checking if the command exit code was unsuccessful
  tags: "terraform_destroy"
