---
- hosts: all
  gather_facts: no
  tasks:
    - include_vars: /home/leroy/UrsaOps/ansible/inventory/group_vars/all.yml
  
- name: Check if group_redir_https exists and has members
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check if group_redir_https has members
      set_fact:
        use_redirector_var: true
      when: 
        - "'group_redir_https' not in groups"
        - "groups['group_redir_https'] is not defined or groups['group_redir_https'] | length == 0"

    - name: Add host from redirector.https variable if group_redir_https is empty
      add_host:
        name: "{{ item }}"
        groups: temp_redir_https_group
      loop: "{{ redirector.https }}"
      when: use_redirector_var | default(false)
  tags:
    - count_redir

- name: Print OK
  hosts: group_redir_https:temp_redir_https_group
  tasks:
    - name: Print
      debug:
        msg: "One Redirector! {{ c2_machine }}"
      when: "'temp_redir_https_group' in group_names"
    - name: Print
      debug:
        msg: "Two Redirector!"
      when: "'group_redir_https' in group_names"

- name: Setup DNS based on provider
  hosts: group_redir_https:temp_redir_https_group
  become: yes
  tasks:
    - include_role:
        name: common
        tasks_from: dns_setup
  tags:
    - dns_setup

- name: Install Nginx Service
  hosts: group_redir_https:temp_redir_https_group
  become: yes
  roles:
    - role: nginx
  tags:
    - setup_nginx

- name: Install Certbot
  hosts: group_redir_https:temp_redir_https_group
  become: yes
  tasks:
    - include_role:
        name: common
        tasks_from: certbot
  tags:
    - certbot

- name: Extract Tailscale IP C2 Server
  hosts: "{{ c2_machine | default('c2srv') }}"
  become: yes
  tasks:
    - name: Check if nodes.yml exists
      command:
        cmd: "tailscale ip --4"
      register: c2srv_ip

    - name: Update group_vars with IP
      delegate_to: localhost
      become: no
      lineinfile:
        path: "{{ ansible_dir }}/inventory/group_vars/c2_segment.yml"
        regexp: '^ip_tailscale_c2:'
        line: "ip_tailscale_c2: \"{{ c2srv_ip.stdout }}\""
  tags:
    - set_ip_c2

- name: Add c2domain.local to /etc/hosts
  hosts: group_redir_https:temp_redir_https_group
  become: yes
  tasks:
    - name: Add c2domain.local to /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: "^.*{{ domain_c2_local | regex_escape() }}.*$"
        line: "{{ ip_tailscale_c2 }} {{ domain_c2_local }}"
        state: present
  tags:
    - add_hosts

- name: Setup Nginx Reverse Proxy
  hosts: group_redir_https:temp_redir_https_group
  vars:
    default_profile: "1"
    profile_value: "{{ profile | default(default_profile) }}"
  become: yes
  tasks:
    - include_role:
        name: nginx
        tasks_from: setup
  tags:
    - setup_redir

- name: Setup CoreDNS for DNS Redirector
  hosts: "{{ redirector.dns | default('redirector_dns') }}"
  become: yes
  tasks:
    - include_role:
        name: coredns
        tasks_from: main
      when: redirdns == 'true'
  tags:
    - setup_coredns

- name: Generate Keystore for CS
  hosts: group_redir_https:temp_redir_https_group
  become: yes
  tasks:
    - include_role:
        name: nginx
        tasks_from: keystore_cs
      when: c2 == 'cobalt'
  tags:
    - keystore_cs

- name: Copy Let's Encrypt Certificates for Sliver C2
  hosts: group_redir_https:temp_redir_https_group
  become: yes
  tasks:
    - name: Copy Let's Encrypt fullchain.pem for Sliver
      fetch:
        src: /etc/letsencrypt/live/{{ domain }}/fullchain.pem
        dest: "{{ ansible_dir }}/roles/c2_sliver/files/cert.pem"
        flat: yes
        mode: "0644"
      when: c2 == 'sliver'

    - name: Copy Let's Encrypt privkey.pem for Sliver
      fetch:
        src: /etc/letsencrypt/live/{{ domain }}/privkey.pem
        dest: "{{ ansible_dir }}/roles/c2_sliver/files/key.pem"
        flat: yes
        mode: "0600"
      when: c2 == 'sliver'
  tags:
    - cert_sliver

- name: Setup C2 [Cobalt Strike 4.7]
  hosts: "{{ c2_machine }}"
  become: yes
  tasks:
    - include_role:
        name: c2_cobalt
        tasks_from: main
      when: c2 == 'cobalt'
  tags:
    - setup_cs

- name: Setup CobaltStrike - Teamserver
  hosts: "{{ c2_machine }}"
  become: yes
  tasks:
    - include_role:
        name: c2_cobalt
        tasks_from: teamserver
      when: c2 == 'cobalt'
  tags:
    - setup_cs

- name: Setup C2 [Havoc]
  hosts: "{{ c2_machine }}"
  become: yes
  vars:
    go_version_18: true
  tasks:
    - include_role:
        name: common
        tasks_from: go
      when: c2 == 'havoc'
    - include_role:
        name: c2_havoc
        tasks_from: main
      when: c2 == 'havoc'
    - include_role:
        name: c2_havoc
        tasks_from: teamserver
      when: c2 == 'havoc'
  tags:
    - setup_havoc

- name: Setup C2 [Sliver]
  hosts: "{{ c2_machine }}"
  become: yes
  tasks:
    - include_role:
        name: c2_sliver
        tasks_from: main
      when: c2 == 'sliver'
  tags:
    - setup_sliver

- name: Disable System Resolved Service
  hosts: "{{ redirector.dns }}"
  become: yes
  tasks:
    - include_role:
        name: common
        tasks_from: system_resolved
      when:
        - redirdns == 'true'
        - c2 == 'sliver'
  tags:
    - disable_resolved

- name: Start CoreDNS
  hosts: "{{ redirector.dns }}"
  become: yes
  tasks:
    - include_role:
        name: coredns
        tasks_from: start
      when:
        - redirdns == 'true'
        - c2 == 'sliver'
  tags:
    - start_coredns
