---
- name: Download Sliver server binary
  get_url:
    url: "https://github.com/BishopFox/sliver/releases/download/{{ version_sliver }}/sliver-server_linux"
    dest: "/usr/local/bin/sliver-server"
    mode: "0755"

- name: Unpack sliver-server
  command: sliver-server unpack --force
  args:
    chdir: /usr/local/bin/

- name: Create sliver service file
  copy:
    dest: "/etc/systemd/system/sliver.service"
    content: |
      [Unit]
      Description=Sliver
      After=network.target
      StartLimitIntervalSec=0

      [Service]
      Type=simple
      Restart=on-failure
      RestartSec=3
      User=root
      ExecStart=/usr/local/bin/sliver-server daemon

      [Install]
      WantedBy=multi-user.target
    mode: "0600"

- name: Start Sliver Server
  command: echo "[+] Starting sliver server"
  notify: start_sliver
  changed_when: true

- name: Delete existing operator profile
  file:
    path: "/tmp/{{ name_sliver_operator }}.cfg"
    state: absent

- name: Create sliver operator profile [Localhost]
  command:
    cmd: sliver-server operator --name {{ name_sliver_operator }} --lhost localhost --save /tmp/{{ name_sliver_operator }}.cfg
  when: jumphost is not defined or not jumphost

- name: Create sliver operator profile [Jumphost]
  command:
    cmd: sliver-server operator --name {{ name_sliver_operator }} --lhost {{ ip_tailscale_c2 }} --save /tmp/{{ name_sliver_operator }}.cfg
  when: jumphost | default(false)

- name: Copy sliver operator profile
  fetch:
    src: /tmp/{{ name_sliver_operator }}.cfg
    dest: "{{ ansible_dir }}/roles/c2_sliver/files/"
    flat: yes

- name: Generate Sliver HTTP Profile from template
  template:
    src: templates/http-c2.j2
    dest: /root/.sliver/configs/http-c2.json
    owner: root
    group: root
    mode: "0600"

- name: Restart Sliver Server
  notify: restart_sliver
  changed_when: true

- name: Setup Sliver Client
  include_tasks: "client.yml"
  when: jumphost is not defined or not jumphost