---
- name: Combine the private key and the certificate into a PKCS12 file
  shell: >
    openssl pkcs12 -export -in /etc/letsencrypt/live/{{ domain }}/fullchain.pem
    -inkey /etc/letsencrypt/live/{{ domain }}/privkey.pem
    -out /tmp/{{ keystore_alias }}.p12
    -name {{ keystore_alias }}
    -passout pass:{{ pkcs12_password }}

- name: Fetch PKCS12 file to localmachine
  fetch:
    src: /tmp/keystore.p12
    dest: ./roles/c2_cobalt/files/keystore.p12
    flat: yes
