---
- name: Install JDK
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - openjdk-17-jre

- name: Check cs archive file
  stat:
    path: /tmp/cobaltstrike47.tar.xz
  register: file_status

- name: Show message if file exists
  debug:
    msg: "Great! The file cobaltstrike47 archive file exists."
  when: file_status.stat.exists

- name: Show message and fail if file does not exist
  fail:
    msg: "The file cobaltstrike47.tar.xz does not exist. Please transfer it using scp/sftp"
  when: not file_status.stat.exists

- name: Extract CS47.tar.xz archive
  unarchive:
    src: /tmp/cobaltstrike47.tar.xz
    dest: /opt/
    remote_src: yes
  when: file_status.stat.exists
