---
- name: Install JDK
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - openjdk-17-jre

- name: Check cs archive file
  stat:
    path: "/tmp/{{ archieve_filename }}"
  register: file_status

- name: Show message if file exists
  debug:
    msg: "Great! The archive file of cobalt strike exists."
  when: file_status.stat.exists

- name: Show message and fail if file does not exist
  fail:
    msg: "The file {{ archieve_filename }} does not exist. Please transfer it using scp/sftp to folder /tmp"
  when: not file_status.stat.exists

- name: Extract CS archive
  unarchive:
    src: "/tmp/{{ archieve_filename }}"
    dest: /opt/
    remote_src: yes
  when: file_status.stat.exists
